---
title: "Welcome to the Vining Lab!"
output: html_document
---


Kelly Vining, Ph.D., is an Associate Professor and Principal Investigator in the [Department of Horticulture](https://horticulture.oregonstate.edu/) at [Oregon State University](https://oregonstate.edu/).
Dr. Vining is also affiliated with the [Global Hemp Innovation Center](https://agsci.oregonstate.edu/hemp), the [Plant Breeding and Genetics](https://plantbreeding.oregonstate.edu/) group, and the [Center for Quantitative Life Sciences](https://cqls.oregonstate.edu/) at Oregon State University.


The Vining Lab integrates powerful tools from genomics and bioinformatics with plant breeding.
The Vining Lab works with a variety of crops important to the Pacific Northwest region of the United States, including mint, hemp, hazelnut, black raspberry, and potato.
Common research themes are identification of disease and pest resistance genes, gene expression studies, and molecular marker development for marker-assisted selection.


Publications from the Vining lab can be found at [Google Scholar](https://scholar.google.com/citations?hl=en&user=gzvZ8jkAAAAJ).



___

[GitHub Code](https://github.com/ViningLab/ViningLab)  - This site on GitHub code.    
[GitHub Pages](https://vininglab.github.io/ViningLab/)  - This site on GitHub pages.    


