---
title: "Reading Group"
date: "`r format(Sys.time(), '%Y, %B %d')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    code_folding: hide
editor_options: 
  chunk_output_type: console
bibliography: ViningLab.bib
---


## Seminars


[Department of Horticulture seminar series](https://horticulture.oregonstate.edu/horticulture-0)    
[Department of Crop and Soil Science seminar series](https://cropandsoil.oregonstate.edu/department-of-crop-and-soil-science/lectures)    
[Department of Botany and Plant Pathology seminar series](https://bpp.oregonstate.edu/bpp/about/seminars)    
[Center for Quantitative Life Sciences seminar series](https://cqls.oregonstate.edu/cqls-seminar-series)    
Note that the CQLS also hosts a spring and fall conference, and other [CQLS events](https://cqls.oregonstate.edu/events)    
[Bioinformatics Users Group (BUG)](https://cqls.oregonstate.edu/training/bioinformatics-users-group-bug)   


## Slack channels

OSU-CQLS-BUG    
Also see: [CQLS tips](https://software.cqls.oregonstate.edu/tips/posts/)



---


## Reading group



### Candidate reading

**CRISPR cas9**

Arora, L. and Narula, A., 2017. Gene editing and crop improvement using CRISPR-Cas9 system. Frontiers in plant science, 8, p.1932. <https://doi.org/10.3389/fpls.2017.01932>

Dort, E.N., Tanguay, P. and Hamelin, R.C., 2020. CRISPR/Cas9 gene editing: an unexplored frontier for forest pathology. Frontiers in Plant Science, 11, p.1126. <https://doi.org/10.3389/fpls.2020.01126>




**Drought tolerance**

Fleury, D., Jefferies, S., Kuchel, H. and Langridge, P., 2010. Genetic and genomic tools to improve drought tolerance in wheat. Journal of experimental botany, 61(12), pp.3211-3222. <https://doi.org/10.1093/jxb/erq152>

Muhammad Ilyas1 · Mohammad Nisar1 · Nadeem Khan1 · Ali Hazrat1 · Aamir Hamid Khan 2 · Kashif Hayat3 · Shah Fahad4 · Aziz Khan5 · Abid Ullah. Drought Tolerance Strategies in Plants: A Mechanistic Approach. Vol.:(0123456789)1 3Journal of Plant Growth Regulation [https://doi.org/10.1007/s00344-020-10174-5](https://doi.org/10.1007/s00344-020-10174-5)

[Insights into Drought Stress Signaling in Plants and
the Molecular Genetic Basis of Cotton
Drought Tolerance](https://mdpi-res.com/d_attachment/cells/cells-09-00105/article_deploy/cells-09-00105-v2.pdf?version=1579343178)


**Genomics**

Barbara McClintock. The origin and behavior of mutable loci in maize. June 1950. 36 (6) 344-355. [https://doi.org/10.1073/pnas.36.6.344](https://doi.org/10.1073/pnas.36.6.344)


Wild emmer genome architecture and diversity elucidate wheat evolution and domestication. Raz Avni, Moran Nave, Omer Barad, Kobi Baruch, Sven O. Twardziok, Heidrun Gundlach, Iago Hale, Martin Mascher, Manuel Spannagl, Assaf Distelfeld.
<https://doi.org/10.1126/science.aan0032>




Hi-C

Belton, J.M., McCord, R.P., Gibcus, J.H., Naumova, N., Zhan, Y. and Dekker, J., 2012. Hi–C: a comprehensive technique to capture the conformation of genomes. Methods, 58(3), pp.268-276. <https://doi.org/10.1016/j.ymeth.2012.05.001>

Pal, K., Forcato, M. and Ferrari, F., 2019. Hi-C analysis: from data generation to integration. Biophysical reviews, 11(1), pp.67-78. <https://doi.org/10.1007/s12551-018-0489-1>

Kronenberg, Z.N., Rhie, A., Koren, S., Concepcion, G.T., Peluso, P., Munson, K.M., Porubsky, D., Kuhn, K., Mueller, K.A., Low, W.Y. and Hiendleder, S., 2021. Extended haplotype-phasing of long-read de novo genome assemblies using Hi-C. Nature communications, 12(1), pp.1-10.
<https://doi.org/10.1038/s41467-020-20536-y>




**Pathology**

Thirty years of resistance: Zig-zag through the plant immune system. Bruno Pok Man Ngou, Pingtao Ding, Jonathan D G Jones. <https://doi.org/10.1093/plcell/koac041>

Plant disease resistance genes: Current status and future directions. Mayank Anand Gururani. Physiological and Molecular Plant Pathology 78 (2012) 51e65. <https://doi.org/10.1016/j.pmpp.2012.01.002>


**Phytochemicals**

Cannabinoids, Phenolics, Terpenes and Alkaloids of Cannabis. Mohamed M Radwan, Suman Chandra, Shahbaz Gul, Mahmoud A ElSohly <https://doi.org/10.3390/molecules26092774>

Secondary metabolism in Cannabis. Isvett Josefina Flores-Sanchez Æ Robert Verpoorte. Phytochem Rev (2008) 7:615–639. <https://doi.org/10.1007/s11101-008-9094-4>


Bautista, J.L., Yu, S. and Tian, L., 2021. Flavonoids in Cannabis sativa: Biosynthesis, bioactivities, and biotechnology. ACS omega, 6(8), pp.5119-5123. <https://doi.org/10.1021/acsomega.1c00318>





### Summer 2022






- 2022-09-15


- 2022-09-01 Lieberman-Aiden, E., Van Berkum, N.L., Williams, L., Imakaev, M., Ragoczy, T., Telling, A., Amit, I., Lajoie, B.R., Sabo, P.J., Dorschner, M.O. and Sandstrom, R., 2009. Comprehensive mapping of long-range interactions reveals folding principles of the human genome. science, 326(5950), pp.289-293. <https://doi.org/10.1126/science.1181369>


- 2022-08-18 Avni, R., Nave, M., Barad, O., Baruch, K., Twardziok, S.O., Gundlach, H., Hale, I., Mascher, M., Spannagl, M., Wiebe, K. and Jordan, K.W., 2017. Wild emmer genome architecture and diversity elucidate wheat evolution and domestication. Science, 357(6346), pp.93-97. <https://doi.org/10.1126/science.aan0032>


- 2022-07-07 Twenty years of plant genome sequencing: achievements and challenges. Yanqing Sun, Lianguang Shang, Qian-Hao Zhu, Longjiang Fan, Longbiao Guo.
<https://doi.org/10.1016/j.tplants.2021.10.006>


- 2022-06-23 [How to read a scientific paper](https://www.science.org/content/article/how-seriously-read-scientific-paper)



### Spring 2022    

- 2022-05-26 [Allen et al. 2019](https://doi.org/10.1371/journal.pone.0222363) Genomic characterization of the complete terpene synthase gene family from Cannabis sativa


- 2022-05-12 [Petit et al. 2020](https://doi.org/10.3389/fgene.2020.566314) Elucidating the Genetic Architecture of Fiber Quality in Hemp (Cannabis sativa L.) Using a Genome-Wide Association Study


- 2022-04-28 [Ejigu and Jung 2020](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7565776/) Review on the Computational Genome Annotation of Sequences Obtained by Next-Generation Sequencing


- 2022-03-31 [Garfinkel et al. 2021](https://doi.org/10.3390/genes12020228). 
SNP in Potentially Defunct Tetrahydrocannabinolic Acid Synthase Is a Marker for Cannabigerolic Acid Dominance in Cannabis sativa L. 


---


# Societal links


[American Association for the Advancement of Science](https://www.aaas.org/) - Organization to advance science, engineering, and innovation throughout the world    
[American Phytopathological Society](https://www.apsnet.org) - Society that studies the diseases of plants    
[American Society of Plant Biologists](https://aspb.org/) - Society that studies plant biology     
[American Society for Horticultural Science](https://ashs.org/) - committed to promoting and encouraging national and international interest in scientific research and education in all branches of horticulture   


---

# Employment opportunities

[www.agcareers.com](https://www.agcareers.com/)    
[www.usajobs](https://www.usajobs.gov/) United States federal government    
[Oregon Department of Agriculture](https://oregon.wd5.myworkdayjobs.com/SOR_External_Career_Site)    
American Phytopathological Society's [career page](https://www.apsnet.org/careers/Pages/default.aspx)    
Glassdoor [salaries page](https://www.glassdoor.com/Salaries/index.htm)    

[Oregon Berry Commision](https://oregon-berries.com/) (Raspberries and blackberries)    
[Oregon Blueberries](https://www.oregonblueberry.com/)    
[Oregon Hazelnuts](https://oregonhazelnuts.org/)    
[Oregon Mint](https://www.oregonmint.org/)    
[Oregon Potato Commision](https://www.oregonspuds.com/)    



---

# OSU [Cultural Resource Centers](https://dce.oregonstate.edu/cultural-resource-centers)


[Asian & Pacific Cultural Center](https://dce.oregonstate.edu/apcc)    
[Centro Cultural César Chávez](https://dce.oregonstate.edu/cccc)    
[Ettihad Cultural Center](https://dce.oregonstate.edu/ecc)    
[Hattie Redmond Women & Gender Center](https://dce.oregonstate.edu/wgc)    
[Kaku-Ixt Mana Ina Haws](https://dce.oregonstate.edu/inahaws)    
[Lonnie B. Harris Black Cultural Center](https://dce.oregonstate.edu/bcc)    
[Pride Center](https://dce.oregonstate.edu/pc)    










